---
# If only one network interface
gateway: 10.12.6.1
netmask: 255.255.255.0
# VMWare default ens192 or ens33
# KVM default ens3
# Libvirt default enp1s0
# Intel NUC default eno1
interface: ens33

dns:
  - 10.12.6.41
  - 10.12.6.42

webserver_url: 10.12.6.88
webserver_port: 8080
# Ignition subpath in http server (optionnal, defaults to nothing)
webserver_ignition_path: /ignition
# Path to download master ignition file will be
# http://192.168.1.20:8080/ignition/master.ign

# Drive to install RHCOS
# Libvirt - can be vda
install_drive: sda

# Timeout for selection menu during first boot
# '-1' for infinite timeout. Default '10'
boot_timeout: 10

# Chose the binary architecture
# x86_64 or ppc64le
arch: "x86_64"

ocp_version: 4.19.23
iso_checksum: 57789e69a859a0c528a9dba7ed688ca964e97c649bcb22ba90e3267bac59b809
iso_checksum_ppc64: ff3ef20a0c4c29022f52ad932278b9040739dc48f4062411b5a3255af863c95e
iso_name: rhcos-{{ ocp_version }}-x86_64-live-iso.x86_64.iso
iso_name_ppc64: rhcos-{{ ocp_version }}-ppc64le-installer.ppc64le.iso
rhcos_bios: rhcos-{{ ocp_version }}-x86_64-metal.x86_64.raw.gz
...